// Generated by scripts/build-browser.js: do not edit.
// rapid-fuzzy for browsers, bundlers and Deno: the wasm-bindgen WebAssembly build.
// The module is instantiated with top-level await, so the API is ready to use
// (synchronously) once the import has resolved.
import init from './rapid-fuzzy-wasm-bindgen.mjs';

// Bundlers (Vite, webpack, Rollup, Parcel) emit the .wasm referenced by this
// `new URL(..., import.meta.url)` as an asset; without a bundler it is fetched
// next to this file.
const wasmUrl = new URL('./rapid-fuzzy-wasm-bindgen_bg.wasm', import.meta.url);
// fetch() cannot read file: URLs in Node.js (e.g. under --conditions=browser);
// read the file directly where the runtime provides process.getBuiltinModule().
const fs = wasmUrl.protocol === 'file:' ? globalThis.process?.getBuiltinModule?.('node:fs') : undefined;
await init({ module_or_path: fs === undefined ? wasmUrl : fs.readFileSync(wasmUrl) });

export {
  FuzzyIndex,
  KeyedFuzzyIndex,
  closest,
  damerauLevenshtein,
  damerauLevenshteinBatch,
  damerauLevenshteinMany,
  hamming,
  hammingBatch,
  hammingMany,
  indel,
  indelBatch,
  indelMany,
  jaro,
  jaroBatch,
  jaroMany,
  jaroWinkler,
  jaroWinklerBatch,
  jaroWinklerMany,
  levenshtein,
  levenshteinBatch,
  levenshteinMany,
  normalizedHamming,
  normalizedHammingBatch,
  normalizedHammingMany,
  normalizedIndel,
  normalizedIndelBatch,
  normalizedIndelMany,
  normalizedLevenshtein,
  normalizedLevenshteinBatch,
  normalizedLevenshteinMany,
  partialRatio,
  partialRatioBatch,
  partialRatioMany,
  search,
  searchKeys,
  sorensenDice,
  sorensenDiceBatch,
  sorensenDiceMany,
  tokenSetRatio,
  tokenSetRatioBatch,
  tokenSetRatioMany,
  tokenSortRatio,
  tokenSortRatioBatch,
  tokenSortRatioMany,
  weightedRatio,
  weightedRatioBatch,
  weightedRatioMany,
  highlight,
  highlightRanges,
  FuzzyObjectIndex,
  searchObjects,
  MatchType,
  levenshteinManyU32,
  damerauLevenshteinManyU32,
  indelManyU32,
  jaroManyF64,
  jaroWinklerManyF64,
  sorensenDiceManyF64,
  normalizedLevenshteinManyF64,
  normalizedIndelManyF64,
  tokenSortRatioManyF64,
  tokenSetRatioManyF64,
  partialRatioManyF64,
  weightedRatioManyF64,
  hammingManyU32,
  normalizedHammingManyF64,
} from './browser-api.mjs';
