// Generated by scripts/build-browser.js: do not edit.
// Declarations of the browser and edge entry points (browser.mjs, workerd.mjs):
// the API of the wasm-bindgen build, without the Node.js-only parts of index.d.ts.
import type { FuzzyObjectIndex as NodeFuzzyObjectIndex } from './objects.js';
import type { MatchType as MatchTypeUnion, damerauLevenshteinMany, hammingMany, indelMany, jaroMany, jaroWinklerMany, levenshteinMany, normalizedHammingMany, normalizedIndelMany, normalizedLevenshteinMany, partialRatioMany, sorensenDiceMany, tokenSetRatioMany, tokenSortRatioMany, weightedRatioMany } from './rapid-fuzzy-wasm-bindgen.mjs';

export {
  FuzzyIndex,
  KeyedFuzzyIndex,
  closest,
  damerauLevenshtein,
  damerauLevenshteinBatch,
  damerauLevenshteinMany,
  hamming,
  hammingBatch,
  hammingMany,
  indel,
  indelBatch,
  indelMany,
  jaro,
  jaroBatch,
  jaroMany,
  jaroWinkler,
  jaroWinklerBatch,
  jaroWinklerMany,
  levenshtein,
  levenshteinBatch,
  levenshteinMany,
  normalizedHamming,
  normalizedHammingBatch,
  normalizedHammingMany,
  normalizedIndel,
  normalizedIndelBatch,
  normalizedIndelMany,
  normalizedLevenshtein,
  normalizedLevenshteinBatch,
  normalizedLevenshteinMany,
  partialRatio,
  partialRatioBatch,
  partialRatioMany,
  search,
  searchKeys,
  sorensenDice,
  sorensenDiceBatch,
  sorensenDiceMany,
  tokenSetRatio,
  tokenSetRatioBatch,
  tokenSetRatioMany,
  tokenSortRatio,
  tokenSortRatioBatch,
  tokenSortRatioMany,
  weightedRatio,
  weightedRatioBatch,
  weightedRatioMany,
} from './rapid-fuzzy-wasm-bindgen.mjs';
export type {
  IndexSearchResult,
  SearchResult,
  KeySearchResult,
  KeyScoreMode,
  KeyMatchMode,
  KeySearchOptions,
  SearchOptions,
} from './rapid-fuzzy-wasm-bindgen.mjs';
export { highlight, highlightRanges } from './highlight.js';
export type {
  HighlightRange,
  HighlightOptions,
} from './highlight.js';
export { searchObjects } from './objects.js';
export type {
  KeyPath,
  KeyConfig,
  ObjectSearchOptions,
  ObjectSearchResult,
  ObjectIndexOptions,
  ObjectIndexSearchOptions,
} from './objects.js';

/**
 * The Node.js `FuzzyObjectIndex` without `serialize()` and `deserialize()`, which
 * exchange Node.js Buffers.
 */
export interface FuzzyObjectIndex<T> extends Omit<NodeFuzzyObjectIndex<T>, 'serialize'> {}
// S and C capture the key names written in the options, like the type parameters
// of the Node.js constructor, so that they are checked against T.
export declare const FuzzyObjectIndex: new <T, S extends string = string, C extends string = string>(
  ...args: ConstructorParameters<typeof NodeFuzzyObjectIndex<T, S, C>>
) => FuzzyObjectIndex<T>;

/** How a search result matched the query. */
export type MatchType = MatchTypeUnion;
/** Runtime values of the {@link MatchType} string enum. */
export declare const MatchType: { readonly Exact: 'Exact'; readonly Prefix: 'Prefix'; readonly Contains: 'Contains'; readonly Fuzzy: 'Fuzzy'; };

/** TypedArray variant of {@link levenshteinMany}: the same function, which already returns a typed array. */
export declare const levenshteinManyU32: typeof levenshteinMany;
/** TypedArray variant of {@link damerauLevenshteinMany}: the same function, which already returns a typed array. */
export declare const damerauLevenshteinManyU32: typeof damerauLevenshteinMany;
/** TypedArray variant of {@link indelMany}: the same function, which already returns a typed array. */
export declare const indelManyU32: typeof indelMany;
/** TypedArray variant of {@link jaroMany}: the same function, which already returns a typed array. */
export declare const jaroManyF64: typeof jaroMany;
/** TypedArray variant of {@link jaroWinklerMany}: the same function, which already returns a typed array. */
export declare const jaroWinklerManyF64: typeof jaroWinklerMany;
/** TypedArray variant of {@link sorensenDiceMany}: the same function, which already returns a typed array. */
export declare const sorensenDiceManyF64: typeof sorensenDiceMany;
/** TypedArray variant of {@link normalizedLevenshteinMany}: the same function, which already returns a typed array. */
export declare const normalizedLevenshteinManyF64: typeof normalizedLevenshteinMany;
/** TypedArray variant of {@link normalizedIndelMany}: the same function, which already returns a typed array. */
export declare const normalizedIndelManyF64: typeof normalizedIndelMany;
/** TypedArray variant of {@link tokenSortRatioMany}: the same function, which already returns a typed array. */
export declare const tokenSortRatioManyF64: typeof tokenSortRatioMany;
/** TypedArray variant of {@link tokenSetRatioMany}: the same function, which already returns a typed array. */
export declare const tokenSetRatioManyF64: typeof tokenSetRatioMany;
/** TypedArray variant of {@link partialRatioMany}: the same function, which already returns a typed array. */
export declare const partialRatioManyF64: typeof partialRatioMany;
/** TypedArray variant of {@link weightedRatioMany}: the same function, which already returns a typed array. */
export declare const weightedRatioManyF64: typeof weightedRatioMany;
/**
 * TypedArray variant of {@link hammingMany}. Slots that `hammingMany` returns as `null`
 * become the sentinel `0xffffffff` (4294967295).
 */
export declare function hammingManyU32(...args: Parameters<typeof hammingMany>): Uint32Array;
/**
 * TypedArray variant of {@link normalizedHammingMany}. Slots that
 * `normalizedHammingMany` returns as `null` become `NaN`.
 */
export declare function normalizedHammingManyF64(
  ...args: Parameters<typeof normalizedHammingMany>
): Float64Array;
