// Pure JS highlight utilities — works in both Node.js and browser environments.
// This file is manually maintained (not auto-generated by napi-rs).

'use strict';

/**
 * @param {string} item
 * @param {number[]} positions
 * @returns {Array<{start: number, end: number, matched: boolean}>}
 */
function highlightRanges(item, positions) {
  if (!item) return [];
  if (!positions || positions.length === 0) {
    return [{ start: 0, end: item.length, matched: false }];
  }

  const set = new Set(positions);
  const ranges = [];
  let i = 0;

  while (i < item.length) {
    const matched = set.has(i);
    const start = i;
    while (i < item.length && set.has(i) === matched) i++;
    ranges.push({ start, end: i, matched });
  }

  return ranges;
}

/**
 * @param {string} item
 * @param {number[]} positions
 * @param {string | ((substring: string) => string)} openOrCallback
 * @param {string} [close]
 * @returns {string}
 */
function highlight(item, positions, openOrCallback, close) {
  if (!positions || positions.length === 0) return item;

  const ranges = highlightRanges(item, positions);
  const useCallback = typeof openOrCallback === 'function';

  const parts = [];
  for (const range of ranges) {
    const segment = item.slice(range.start, range.end);
    if (range.matched) {
      parts.push(useCallback ? openOrCallback(segment) : openOrCallback + segment + (close ?? ''));
    } else {
      parts.push(segment);
    }
  }

  return parts.join('');
}

module.exports.highlight = highlight;
module.exports.highlightRanges = highlightRanges;
