/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A persistent fuzzy search index backed by Rust-side data.
 *
 * Holds items in memory on the Rust side, avoiding repeated FFI overhead
 * for applications that search the same dataset multiple times.
 * Pre-computes Utf32String representations for each item, eliminating
 * per-search string conversion overhead.
 * Memory is freed when the JavaScript garbage collector collects the instance
 * or when `destroy()` is called explicitly.
 */
export declare class FuzzyIndex {
  /** Create a new FuzzyIndex from an array of strings. */
  constructor(items: Array<string>)
  /** Return the number of items in the index. */
  get size(): number
  /**
   * Search the index for items matching the query.
   *
   * Returns matches sorted by score (best match first).
   * Scores are normalized to a 0.0-1.0 range where 1.0 is a perfect match.
   */
  search(query: string, options?: number | SearchOptions | undefined | null): Array<SearchResult>
  /**
   * Find the closest matching string in the index.
   *
   * Returns the best match, or null if no match is found.
   * If minScore is provided, returns null when the best match scores below the threshold.
   */
  closest(query: string, minScore?: number | undefined | null): string | null
  /** Add a single item to the index. */
  add(item: string): void
  /** Add multiple items to the index at once. */
  addMany(items: Array<string>): void
  /**
   * Remove the item at the given index.
   *
   * Returns false if the index is out of bounds.
   */
  remove(index: number): boolean
  /** Free the internal data. After calling this, the index is empty. */
  destroy(): void
  /**
   * Serialize the index to a compact binary format.
   *
   * The returned Buffer can be written to disk, stored in IndexedDB,
   * or transferred over the network. Use `FuzzyIndex.deserialize()` to
   * reconstruct the index.
   */
  serialize(): Buffer
  /**
   * Reconstruct a FuzzyIndex from a previously serialized Buffer.
   *
   * Pre-computes Utf32String and character masks from the stored items,
   * so the returned index is immediately ready for searching.
   */
  static deserialize(data: Buffer): FuzzyIndex
}

/**
 * A persistent multi-key fuzzy search index backed by Rust-side data.
 *
 * Holds key text arrays and weights in memory on the Rust side,
 * avoiding repeated FFI overhead for applications that search the
 * same dataset multiple times with multiple keys.
 * Pre-computes Utf32String representations and reuses the Matcher
 * instance for optimal repeated-search performance.
 *
 * Typically wrapped by a JS-side `FuzzyObjectIndex` class that maps
 * results back to original objects.
 */
export declare class KeyedFuzzyIndex {
  /**
   * Create a new KeyedFuzzyIndex.
   *
   * `key_texts[k]` is an array of strings for key `k`, one per item.
   * All inner arrays must have the same length (the number of items).
   */
  constructor(keyTexts: Array<Array<string>>, weights: Array<number>)
  /** Return the number of items in the index. */
  get size(): number
  /**
   * Search the index for items matching the query.
   *
   * Returns results sorted by combined weighted score (best match first).
   */
  search(query: string, options?: SearchOptions | undefined | null): Array<KeySearchResult>
  /**
   * Add a single item to the index.
   *
   * `key_values` must have the same length as the number of keys.
   * Throws if the length does not match.
   */
  add(keyValues: Array<string>): void
  /**
   * Add multiple items to the index at once.
   *
   * Each element of `items_key_values` is an array of key values for one item.
   * Throws if any element has the wrong number of key values.
   */
  addMany(itemsKeyValues: Array<Array<string>>): void
  /**
   * Remove the item at the given index.
   *
   * Uses swap-remove for O(1) performance. Returns false if out of bounds.
   */
  remove(index: number): boolean
  /** Free the internal data. After calling this, the index is empty. */
  destroy(): void
}

/**
 * Find the closest matching string from a list.
 *
 * Returns the best match, or null if no match is found.
 * If minScore is provided, returns null when the best match scores below the threshold.
 */
export declare function closest(query: string, items: Array<string>, minScore?: number | undefined | null): string | null

/**
 * Compute the Damerau-Levenshtein distance between two strings.
 *
 * Like Levenshtein, but also considers transpositions of two adjacent
 * characters as a single edit.
 */
export declare function damerauLevenshtein(a: string, b: string): number

/**
 * Compute the Damerau-Levenshtein distance for multiple pairs of strings in a single call.
 *
 * Returns an array of distances in the same order as the input pairs.
 */
export declare function damerauLevenshteinBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Damerau-Levenshtein distance from one reference string to many candidates.
 *
 * Returns an array of distances, one per candidate, in the same order as the input.
 * If `max_distance` is provided, candidates with distance exceeding the threshold
 * will return `max_distance + 1` (enabling early termination for better performance).
 */
export declare function damerauLevenshteinMany(reference: string, candidates: Array<string>, maxDistance?: number | undefined | null): Array<number>

/**
 * Compute the Jaro similarity between two strings.
 *
 * Returns a value between 0.0 (completely different) and 1.0 (identical).
 */
export declare function jaro(a: string, b: string): number

/**
 * Compute the Jaro similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function jaroBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Jaro similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `min_similarity` is provided, candidates with similarity below the threshold
 * will return `0.0` (enabling early termination for better performance).
 */
export declare function jaroMany(reference: string, candidates: Array<string>, minSimilarity?: number | undefined | null): Array<number>

/**
 * Compute the Jaro-Winkler similarity between two strings.
 *
 * A modification of Jaro that gives more weight to common prefixes.
 * Returns a value between 0.0 and 1.0.
 */
export declare function jaroWinkler(a: string, b: string): number

/**
 * Compute the Jaro-Winkler similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function jaroWinklerBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Jaro-Winkler similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `min_similarity` is provided, candidates with similarity below the threshold
 * will return `0.0` (enabling early termination for better performance).
 */
export declare function jaroWinklerMany(reference: string, candidates: Array<string>, minSimilarity?: number | undefined | null): Array<number>

/** A single result from multi-key fuzzy search. */
export interface KeySearchResult {
  /** The index of the item in the original input array. */
  index: number
  /** The combined weighted score normalized to 0.0-1.0 range. */
  score: number
  /**
   * Per-key scores in the same order as the input keys.
   * A score of 0.0 means the item did not match on that key.
   */
  keyScores: Array<number>
}

/**
 * Compute the Levenshtein distance between two strings.
 *
 * The Levenshtein distance is the minimum number of single-character edits
 * (insertions, deletions, or substitutions) required to change one string
 * into the other.
 */
export declare function levenshtein(a: string, b: string): number

/**
 * Compute the Levenshtein distance for multiple pairs of strings in a single call.
 *
 * Returns an array of distances in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`.
 */
export declare function levenshteinBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Levenshtein distance from one reference string to many candidates.
 *
 * Returns an array of distances, one per candidate, in the same order as the input.
 * If `max_distance` is provided, candidates with distance exceeding the threshold
 * will return `max_distance + 1` (enabling early termination for better performance).
 */
export declare function levenshteinMany(reference: string, candidates: Array<string>, maxDistance?: number | undefined | null): Array<number>

/**
 * Classification of how a query matched an item.
 *
 * Derived from the matched character positions:
 * - **Exact**: all positions consecutive from index 0, covering every character in the item.
 * - **Prefix**: all positions consecutive from index 0, but the item is longer.
 * - **Contains**: all positions consecutive (a substring match), not starting at 0.
 * - **Fuzzy**: positions have gaps (character-level fuzzy match).
 */
export declare const enum MatchType {
  Exact = 'Exact',
  Prefix = 'Prefix',
  Contains = 'Contains',
  Fuzzy = 'Fuzzy'
}

/**
 * Compute the normalized Levenshtein similarity between two strings.
 *
 * Returns a value between 0.0 (completely different) and 1.0 (identical).
 */
export declare function normalizedLevenshtein(a: string, b: string): number

/**
 * Compute the normalized Levenshtein similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function normalizedLevenshteinBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the normalized Levenshtein similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `min_similarity` is provided, candidates with similarity below the threshold
 * will return `0.0` (enabling early termination for better performance).
 */
export declare function normalizedLevenshteinMany(reference: string, candidates: Array<string>, minSimilarity?: number | undefined | null): Array<number>

/**
 * Compute the partial ratio between two strings.
 *
 * Finds the best matching substring of the shorter string within the longer string
 * using a sliding window approach. Returns the highest normalized Levenshtein
 * similarity across all windows. Useful for matching when one string is a
 * substring or abbreviation of the other. Returns a value between 0.0 and 1.0.
 */
export declare function partialRatio(a: string, b: string): number

/**
 * Compute the partial ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function partialRatioBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the partial ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function partialRatioMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Perform fuzzy search over a list of strings.
 *
 * Returns matches sorted by score (best match first).
 * Scores are normalized to a 0.0-1.0 range where 1.0 is a perfect match.
 * Uses the nucleo algorithm (same as Helix editor), which is
 * significantly faster than fzf/skim for large datasets.
 *
 * The third argument accepts either a number (maxResults for backward
 * compatibility) or a SearchOptions object with maxResults and minScore.
 */
export declare function search(query: string, items: Array<string>, options?: number | SearchOptions | undefined | null): Array<SearchResult>

/**
 * Perform fuzzy search across multiple text keys with weights.
 *
 * `key_texts[k]` is an array of strings for key `k`, one per item.
 * All inner arrays must have the same length (the number of items).
 * `weights` specifies the relative importance of each key.
 *
 * Returns results sorted by combined weighted score (best match first).
 */
export declare function searchKeys(query: string, keyTexts: Array<Array<string>>, weights: Array<number>, options?: SearchOptions | undefined | null): Array<KeySearchResult>

/** Options for the search function. */
export interface SearchOptions {
  /** Maximum number of results to return. */
  maxResults?: number
  /** Minimum normalized score (0.0-1.0) to include in results. */
  minScore?: number
  /** If true, include matched character positions in results. */
  includePositions?: boolean
  /**
   * If true, matching is case-sensitive. Default is smart case
   * (case-insensitive unless the query contains uppercase characters).
   */
  isCaseSensitive?: boolean
  /**
   * If true, return all items when the query is empty (or whitespace-only).
   * Useful for filter-as-you-type UIs where the full list should appear
   * before the user starts typing. Default is false.
   */
  returnAllOnEmpty?: boolean
}

/** A single fuzzy search result with the matched item and its score. */
export interface SearchResult {
  /** The original string that matched. */
  item: string
  /** The match score normalized to 0.0-1.0 range (1.0 is a perfect match). */
  score: number
  /** The index of the item in the original input array. */
  index: number
  /**
   * Indices of matched characters in the item string.
   * Empty unless `includePositions` is set to true in SearchOptions.
   */
  positions: Array<number>
  /**
   * How the query matched this item (Exact, Prefix, Contains, or Fuzzy).
   * Only present when `includePositions` is set to true in SearchOptions.
   * Derived from positions at zero additional cost.
   */
  matchType?: MatchType
}

/**
 * Compute the Sorensen-Dice coefficient between two strings.
 *
 * Uses bigrams (pairs of consecutive characters) to measure similarity.
 * Returns a value between 0.0 and 1.0.
 */
export declare function sorensenDice(a: string, b: string): number

/**
 * Compute the Sorensen-Dice coefficient for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function sorensenDiceBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Sorensen-Dice coefficient from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function sorensenDiceMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the token set ratio between two strings.
 *
 * Compares the intersection and differences of token sets from both strings.
 * Returns the maximum similarity among comparisons of the intersection with
 * each remainder. Highly effective for strings with shared tokens but
 * different lengths. Returns a value between 0.0 and 1.0.
 */
export declare function tokenSetRatio(a: string, b: string): number

/**
 * Compute the token set ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function tokenSetRatioBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the token set ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function tokenSetRatioMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the token sort ratio between two strings.
 *
 * Splits both strings into tokens, sorts them alphabetically, then computes
 * the normalized Levenshtein similarity. This makes the comparison
 * order-independent, ideal for matching names or addresses where word order varies.
 * Returns a value between 0.0 (completely different) and 1.0 (identical after sorting).
 */
export declare function tokenSortRatio(a: string, b: string): number

/**
 * Compute the token sort ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function tokenSortRatioBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the token sort ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function tokenSortRatioMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the weighted ratio between two strings.
 *
 * Returns the maximum score across normalized Levenshtein, token sort ratio,
 * token set ratio, and partial ratio. This provides a single "best effort"
 * similarity score that automatically selects the most appropriate algorithm.
 * Returns a value between 0.0 and 1.0.
 */
export declare function weightedRatio(a: string, b: string): number

/**
 * Compute the weighted ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function weightedRatioBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the weighted ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function weightedRatioMany(reference: string, candidates: Array<string>): Array<number>

// --- JS utilities (appended by scripts/patch-binding.js) ---
export { highlight, highlightRanges, HighlightRange } from './highlight';
