/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * A persistent fuzzy search index backed by Rust-side data.
 *
 * Holds items in memory on the Rust side, avoiding repeated FFI overhead
 * for applications that search the same dataset multiple times.
 * Pre-computes the search representation of each item (a character mask,
 * plus the UTF-32 text of non-ASCII items), eliminating per-search string
 * conversion overhead.
 * Memory is freed when the JavaScript garbage collector collects the instance
 * or when `destroy()` is called explicitly.
 */
export declare class FuzzyIndex {
  /** Create a new FuzzyIndex from an array of strings. */
  constructor(items: ReadonlyArray<string>)
  /**
   * Construct a FuzzyIndex on the libuv thread pool, returning a Promise.
   *
   * For large datasets this keeps the JavaScript event loop unblocked during
   * index construction. The synchronous constructor is fine for small datasets.
   *
   * Invalid input (such as an array containing a non-string) rejects the
   * returned Promise instead of throwing synchronously.
   */
  static fromAsync(items: ReadonlyArray<string>): Promise<FuzzyIndex>
  /** Return the number of items in the index. */
  get size(): number
  /**
   * Search the index for items matching the query.
   *
   * Returns matches sorted by score (best match first).
   * Scores are normalized to a 0.0-1.0 range where 1.0 is a perfect match.
   *
   * Results are identical to `search(query, items, options)` over the same
   * items, including the query syntax and whitespace rules.
   *
   * The second argument accepts either a number (maxResults shorthand) or a
   * SearchOptions object. `maxResults` must be a non-negative integer or
   * `Infinity`.
   */
  search(query: string, options?: number | SearchOptions | undefined | null): Array<SearchResult>
  /**
   * Find the closest matching string in the index.
   *
   * Returns the best match, or null if no match is found.
   * If minScore is provided, returns null when the best match scores below the threshold.
   */
  closest(query: string, minScore?: number | undefined | null): string | null
  /**
   * Search the index, returning only indices and scores (no item strings).
   *
   * This is more efficient than `search()` when you maintain your own data
   * array and only need the index to look up the original item. Avoids
   * String cloning overhead for each result.
   *
   * The second argument accepts either a number (maxResults shorthand) or a
   * SearchOptions object. `maxResults` must be a non-negative integer or
   * `Infinity`.
   */
  searchIndices(query: string, options?: number | SearchOptions | undefined | null): Array<IndexSearchResult>
  /** Add a single item to the index. */
  add(item: string): void
  /** Add multiple items to the index at once. */
  addMany(items: ReadonlyArray<string>): void
  /**
   * Remove the item at the given index.
   *
   * Uses swap-remove for O(1) performance. Returns false if out of bounds.
   */
  remove(index: number): boolean
  /**
   * Free the internal data. After calling this, the index is empty.
   *
   * The index stays usable: it behaves as an empty index (searches
   * return no results) and `add()` / `addMany()` work as before.
   */
  destroy(): void
  /**
   * Serialize the index to a compact binary format.
   *
   * The returned Buffer can be written to disk, stored in IndexedDB,
   * or transferred over the network. Use `FuzzyIndex.deserialize()` to
   * reconstruct the index.
   *
   * The format stores the item strings (UTF-8, each with a 4-byte length)
   * after a small header, not the precomputed search data:
   * `deserialize()` recomputes it, so loading takes about as long as
   * building the index from an array. The format is versioned; data
   * written by a different format version is rejected.
   */
  serialize(): Buffer
  /**
   * Reconstruct a FuzzyIndex from a previously serialized Buffer.
   *
   * Pre-computes the search representation of the stored items,
   * so the returned index is immediately ready for searching.
   */
  static deserialize(data: Buffer): FuzzyIndex
}

/**
 * A persistent multi-key fuzzy search index backed by Rust-side data.
 *
 * Holds key text arrays and weights in memory on the Rust side,
 * avoiding repeated FFI overhead for applications that search the
 * same dataset multiple times with multiple keys.
 * Pre-computes the search representation of every key text, eliminating
 * per-search string conversion overhead.
 * Memory is freed when the JavaScript garbage collector collects the instance
 * or when `destroy()` is called explicitly.
 *
 * Typically wrapped by a JS-side `FuzzyObjectIndex` class that maps
 * results back to original objects.
 */
export declare class KeyedFuzzyIndex {
  /**
   * Create a new KeyedFuzzyIndex.
   *
   * `keyTexts[k]` is an array of strings for key `k`, one per item.
   * All inner arrays must have the same length (the number of items).
   */
  constructor(keyTexts: ReadonlyArray<ReadonlyArray<string>>, weights: ReadonlyArray<number>)
  /** Return the number of items in the index. */
  get size(): number
  /**
   * Search the index for items matching the query.
   *
   * Returns results sorted by combined score (best match first), exactly
   * like `searchKeys()` on the same key texts and weights.
   *
   * The second argument accepts either a number (maxResults shorthand) or a
   * KeySearchOptions object, whose `matchMode` selects how the query is
   * matched against the keys and `scoreMode` how the per-key scores are
   * combined. `maxResults` must be a non-negative integer or `Infinity`.
   */
  search(query: string, options?: number | KeySearchOptions | undefined | null): Array<KeySearchResult>
  /**
   * Find the index of the closest matching item.
   *
   * Returns the index of the best match, or null if no match is found:
   * the index of the first result of
   * `search(query, { maxResults: 1, minScore, scoreMode, matchMode })`.
   *
   * The second argument accepts either a number (minScore shorthand) or a
   * KeyClosestOptions object: `minScore` makes it return null when the
   * best match scores below the threshold, and `scoreMode` and
   * `matchMode` work like the `search()` options of the same names
   * (defaults `'weighted'` and `'perKey'`).
   *
   * Use the returned index to look up the item in your own data array.
   */
  closest(query: string, options?: number | KeyClosestOptions | undefined | null): number | null
  /**
   * Add a single item to the index.
   *
   * `keyValues` must have the same length as the number of keys.
   * Throws if the length does not match.
   */
  add(keyValues: ReadonlyArray<string>): void
  /**
   * Add multiple items to the index at once.
   *
   * Each element of `itemsKeyValues` is an array of key values for one item.
   * Throws if any element has the wrong number of key values; every element
   * is checked first, so on error no item is added.
   */
  addMany(itemsKeyValues: ReadonlyArray<ReadonlyArray<string>>): void
  /**
   * Remove the item at the given index.
   *
   * Uses swap-remove for O(1) performance. Returns false if out of bounds.
   */
  remove(index: number): boolean
  /**
   * Free the internal data. After calling this, the index is empty.
   *
   * The key configuration is kept, so the index stays usable: it behaves
   * as an empty index and `add()` / `addMany()` work as before.
   */
  destroy(): void
  /**
   * Serialize the index to a compact binary format.
   *
   * The returned Buffer can be written to disk, stored in IndexedDB,
   * or transferred over the network. Use `KeyedFuzzyIndex.deserialize()` to
   * reconstruct the index.
   */
  serialize(): Buffer
  /** Reconstruct a KeyedFuzzyIndex from a previously serialized Buffer. */
  static deserialize(data: Buffer): KeyedFuzzyIndex
}

/**
 * Find the closest matching string from a list.
 *
 * Returns the best match, or null if no match is found.
 * If minScore is provided, returns null when the best match scores below the threshold.
 */
export declare function closest(query: string, items: ReadonlyArray<string>, minScore?: number | undefined | null): string | null

/**
 * Compute the Damerau-Levenshtein distance between two strings.
 *
 * Like Levenshtein, but also considers transpositions of two adjacent
 * characters as a single edit.
 *
 * Compares the Unicode code points of the strings as given: case, whitespace
 * and Unicode normalization (NFC vs NFD) are not adjusted.
 * Takes time proportional to the product of the two lengths: about 0.4 s
 * for two 10,000-character strings with the native addon.
 */
export declare function damerauLevenshtein(a: string, b: string): number

/**
 * Compute the Damerau-Levenshtein distance for multiple pairs of strings in a single call.
 *
 * Returns an array of distances in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function damerauLevenshteinBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the Damerau-Levenshtein distance from one reference string to many candidates.
 *
 * Returns an array of distances, one per candidate, in the same order as the input.
 * If `maxDistance` is provided, candidates with distance exceeding the threshold
 * will return `maxDistance + 1`, at most 4294967295 (enabling early termination
 * for better performance).
 */
export declare function damerauLevenshteinMany(reference: string, candidates: ReadonlyArray<string>, maxDistance?: number | undefined | null): Array<number>

/** Like `damerauLevenshteinMany`, but returns the distances in a `Uint32Array`. */
export declare function damerauLevenshteinManyU32(reference: string, candidates: ReadonlyArray<string>, maxDistance?: number | undefined | null): Uint32Array

/**
 * Compute the Hamming distance between two strings.
 *
 * The Hamming distance counts the number of positions at which the corresponding
 * characters differ. It is only defined for strings of equal length.
 * Returns `null` if the strings have different lengths.
 *
 * Compares the Unicode code points of the strings as given: case, whitespace
 * and Unicode normalization (NFC vs NFD) are not adjusted.
 */
export declare function hamming(a: string, b: string): number | null

/**
 * Compute the Hamming distance for multiple pairs of strings in a single call.
 *
 * Returns an array of distances in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 * Returns `null` for pairs with different lengths.
 */
export declare function hammingBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number | undefined | null>

/**
 * Compute the Hamming distance from one reference string to many candidates.
 *
 * Returns an array of distances, one per candidate, in the same order as the input.
 * Returns `null` for candidates with a different length than the reference.
 * If `maxDistance` is provided, candidates with distance exceeding the threshold
 * will also return `null` (enabling early termination for better performance).
 */
export declare function hammingMany(reference: string, candidates: ReadonlyArray<string>, maxDistance?: number | undefined | null): Array<number | undefined | null>

/**
 * Like `hammingMany`, but returns the distances in a `Uint32Array`.
 *
 * Slots that `hammingMany` returns as `null` (length mismatch, or filtered out
 * by `maxDistance`) become the sentinel `0xffffffff` (4294967295), since a
 * Uint32Array cannot hold `null`. Check for it with `value === 0xffffffff`
 * before treating a slot as a real distance.
 */
export declare function hammingManyU32(reference: string, candidates: ReadonlyArray<string>, maxDistance?: number | undefined | null): Uint32Array

/**
 * Compute the Indel distance between two strings.
 *
 * The Indel distance counts the minimum number of insertions and deletions
 * (no substitutions) required to transform one string into the other.
 * It equals `len(a) + len(b) - 2 * LCS_length(a, b)`.
 *
 * Useful when substitutions are semantically two operations (one deletion +
 * one insertion), such as in DNA sequence alignment.
 *
 * Compares the Unicode code points of the strings as given: case, whitespace
 * and Unicode normalization (NFC vs NFD) are not adjusted.
 */
export declare function indel(a: string, b: string): number

/**
 * Compute the Indel distance for multiple pairs of strings in a single call.
 *
 * Returns an array of distances in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function indelBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the Indel distance from one reference string to many candidates.
 *
 * Returns an array of distances, one per candidate, in the same order as the input.
 * If `maxDistance` is provided, candidates with distance exceeding the threshold
 * will return `maxDistance + 1`, at most 4294967295 (enabling early termination
 * for better performance).
 */
export declare function indelMany(reference: string, candidates: ReadonlyArray<string>, maxDistance?: number | undefined | null): Array<number>

/** Like `indelMany`, but returns the distances in a `Uint32Array`. */
export declare function indelManyU32(reference: string, candidates: ReadonlyArray<string>, maxDistance?: number | undefined | null): Uint32Array

/**
 * A lightweight search result containing only index and score (no item string).
 *
 * Use this when you maintain your own data array and only need the index
 * to look up the original item. Avoids String cloning overhead.
 */
export interface IndexSearchResult {
  /** The index of the item in the original input array. */
  index: number
  /** The match score normalized to 0.0-1.0 range (1.0 is a perfect match). */
  score: number
  /**
   * Indices of the matched characters of the item, in ascending order.
   * An ASCII item is counted by character; any other item by grapheme
   * cluster (a user-perceived character, such as an emoji with its
   * modifiers or a letter with its combining marks), so these are not
   * UTF-16 string offsets. `highlight()` and `highlightRanges()` convert
   * them. Empty unless `includePositions` is set to true in SearchOptions.
   */
  positions: Array<number>
  /**
   * How the query matched this item (Exact, Prefix, Contains, or Fuzzy).
   * Only present when `includePositions` is set to true in SearchOptions.
   * Derived from positions at zero additional cost.
   */
  matchType?: MatchType
}

/**
 * Compute the Jaro similarity between two strings.
 *
 * Returns a value between 0.0 (completely different) and 1.0 (identical).
 *
 * Compares the Unicode code points of the strings as given: case, whitespace
 * and Unicode normalization (NFC vs NFD) are not adjusted.
 */
export declare function jaro(a: string, b: string): number

/**
 * Compute the Jaro similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function jaroBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the Jaro similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `minSimilarity` is provided, candidates with similarity below the threshold
 * will return `0.0` (enabling early termination for better performance); a score
 * equal to it is kept. Throws an `InvalidArg` error if `minSimilarity` is `NaN`.
 */
export declare function jaroMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number>

/** Like `jaroMany`, but returns the scores in a `Float64Array`. */
export declare function jaroManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

/**
 * Compute the Jaro-Winkler similarity between two strings.
 *
 * A modification of Jaro that gives more weight to common prefixes.
 * Returns a value between 0.0 and 1.0.
 *
 * Compares the Unicode code points of the strings as given: case, whitespace
 * and Unicode normalization (NFC vs NFD) are not adjusted.
 */
export declare function jaroWinkler(a: string, b: string): number

/**
 * Compute the Jaro-Winkler similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function jaroWinklerBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the Jaro-Winkler similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `minSimilarity` is provided, candidates with similarity below the threshold
 * will return `0.0` (enabling early termination for better performance); a score
 * equal to it is kept. Throws an `InvalidArg` error if `minSimilarity` is `NaN`.
 */
export declare function jaroWinklerMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number>

/** Like `jaroWinklerMany`, but returns the scores in a `Float64Array`. */
export declare function jaroWinklerManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

/**
 * Options for `KeyedFuzzyIndex.closest()` and `FuzzyObjectIndex.closest()`:
 * the `KeySearchOptions` fields that apply to finding the best match. The
 * result is the first result of `search()` with these options and
 * `maxResults: 1`. Other `KeySearchOptions` fields are not read.
 */
export interface KeyClosestOptions {
  /**
   * Minimum combined score (0.0-1.0, see `scoreMode`): `closest()`
   * returns null when the best match scores below it.
   */
  minScore?: number | undefined
  /**
   * How the per-key scores of an item are combined into its score:
   * `'weighted'` (default), `'matched'` or `'max'`, as in
   * `KeySearchOptions.scoreMode`. Any other value throws an `InvalidArg`
   * error.
   */
  scoreMode?: KeyScoreMode | undefined
  /**
   * How the query is matched against the keys of an item: `'perKey'`
   * (default) or `'crossKey'`, as in `KeySearchOptions.matchMode`. Any
   * other value throws an `InvalidArg` error.
   */
  matchMode?: KeyMatchMode | undefined
}

/**
 * Options for multi-key search: `searchKeys()`, `KeyedFuzzyIndex.search()`
 * and the object search built on them (`searchObjects()`,
 * `FuzzyObjectIndex.search()`). The `SearchOptions` fields, plus
 * `scoreMode` and `matchMode`.
 */
export interface KeySearchOptions {
  /**
   * Maximum number of results to return: a non-negative integer, or
   * `Infinity` for no limit. NaN, negative and fractional values throw.
   */
  maxResults?: number | undefined
  /**
   * Minimum combined score (0.0-1.0, see `scoreMode`) to include in
   * results.
   */
  minScore?: number | undefined
  /**
   * Accepted for compatibility with `SearchOptions`, but has no effect:
   * multi-key results have no match positions.
   */
  includePositions?: boolean | undefined
  /**
   * If true, matching is case-sensitive. When false or omitted, matching
   * is smart case: case-insensitive while the query is all lower-case, and
   * case-sensitive once it contains an upper-case letter. `false` does not
   * force case-insensitive matching; lower-case the query for that.
   */
  isCaseSensitive?: boolean | undefined
  /**
   * If true, return all items when the query has no search term: empty,
   * whitespace-only, or only query syntax such as `^` or `!`. Every item
   * then scores 1, in every `scoreMode`. Default is false.
   */
  returnAllOnEmpty?: boolean | undefined
  /**
   * How the per-key scores (`keyScores`) of an item are combined into its
   * `score`. Only keys with a positive weight take part:
   *
   * - `'weighted'` (default): the weighted mean over all keys,
   *   `sum(weight * keyScore) / sum(weight)`. A key that does not match
   *   counts as 0, so an exact match on one key out of several scores only
   *   that key's share of the total weight.
   * - `'matched'`: the weighted mean over the keys that match
   *   (`keyScore > 0`) only. An item whose only matching key matches
   *   exactly scores 1.
   * - `'max'`: the highest score of any key. Weights then only select the
   *   keys that take part (weight > 0).
   *
   * `keyScores` are the same in every mode; `minScore` and `maxResults`
   * apply to the combined score. Equal scores are ordered by the UTF-8
   * byte length of the best-matching key's text (the key contributing
   * most to the score: highest `weight * keyScore`, or highest `keyScore`
   * in `'max'` mode; the first one on a tie), then by index. Any other
   * value throws an `InvalidArg` error.
   *
   * With `matchMode: 'crossKey'`, `'matched'` counts the weight of each
   * key in proportion to the share of the query it matches, and `'max'`
   * scores each term by the key it matches best (see `matchMode`).
   */
  scoreMode?: KeyScoreMode | undefined
  /**
   * How the query is matched against the keys of an item:
   *
   * - `'perKey'` (default): every key is matched against the whole query,
   *   like `search()` matches an item. A key scores 0 unless it matches
   *   every term of the query and none of its `!term` exclusions.
   * - `'crossKey'`: every term is matched against the keys on its own, so
   *   the terms may match different keys: `'john tokyo'` finds an item
   *   whose name is "John Smith" and whose city is "Tokyo". Every term
   *   must match at least one key, and a `!term` matching any key
   *   excludes the item. A key's score (`keyScores`) is the share of the
   *   query it matches: the scores of the terms it matches, each counting
   *   in proportion to the score of a perfect match of the term (which
   *   grows with its length), so a key matching every term perfectly
   *   scores 1. `scoreMode` combines these key scores: `'weighted'` as
   *   `sum(weight * keyScore) / sum(weight)`, as in `'perKey'` mode;
   *   `'matched'` as `sum(weight * keyScore) / sum(weight * coverage)`,
   *   where a key's coverage is the share of the query made up by the
   *   terms it matches (in `'perKey'` mode, 1 for a key that matches and
   *   0 otherwise); `'max'` by taking each term's score on the key it
   *   matches best. In `'max'` mode, an item whose every term matches some
   *   key perfectly scores 1. In `'matched'` mode, only an item whose
   *   every term matches perfectly each key it matches scores 1: a term
   *   that also matches another key partially lowers the score, so
   *   `'john tokyo'` scores 0.89 on an item whose name is "John Smith",
   *   whose city is "Tokyo" and whose email "jtokyo@example.com" matches
   *   `tokyo` partially.
   *
   * Only keys with a positive weight take part in either mode; keys whose
   * weight is 0 still get `keyScores`. For a query of a single term
   * without exclusions, both modes return the same results. Any other
   * value throws an `InvalidArg` error.
   */
  matchMode?: KeyMatchMode | undefined
}

/**
 * How multi-key search (`searchKeys()`, `KeyedFuzzyIndex`, `searchObjects()`,
 * `FuzzyObjectIndex`) matches the query against the keys of an item:
 * `'perKey'` (the default: every key against the whole query) or
 * `'crossKey'` (every term against the keys on its own). See
 * `KeySearchOptions.matchMode`.
 */
export type KeyMatchMode = 'perKey' | 'crossKey'

/**
 * How multi-key search (`searchKeys()`, `KeyedFuzzyIndex`, `searchObjects()`,
 * `FuzzyObjectIndex`) combines the per-key scores of an item into its score:
 * `'weighted'` (the default), `'matched'` or `'max'`. See
 * `KeySearchOptions.scoreMode`.
 */
export type KeyScoreMode = 'weighted' | 'matched' | 'max'

/** A single result from multi-key fuzzy search. */
export interface KeySearchResult {
  /** The index of the item in the original input array. */
  index: number
  /**
   * The combined score (0.0-1.0) of the key scores, as set by
   * `scoreMode` (by default the weighted mean over all keys).
   */
  score: number
  /**
   * Per-key scores in the same order as the input keys: how well each
   * key matches the query (with `matchMode: 'crossKey'`, the share of the
   * query it matches). A score of 0.0 means the item did not match on
   * that key.
   */
  keyScores: Array<number>
}

/**
 * Compute the Levenshtein distance between two strings.
 *
 * The Levenshtein distance is the minimum number of single-character edits
 * (insertions, deletions, or substitutions) required to change one string
 * into the other.
 *
 * Compares the Unicode code points of the strings as given: case, whitespace
 * and Unicode normalization (NFC vs NFD) are not adjusted.
 */
export declare function levenshtein(a: string, b: string): number

/**
 * Compute the Levenshtein distance for multiple pairs of strings in a single call.
 *
 * Returns an array of distances in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function levenshteinBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the Levenshtein distance from one reference string to many candidates.
 *
 * Returns an array of distances, one per candidate, in the same order as the input.
 * If `maxDistance` is provided, candidates with distance exceeding the threshold
 * will return `maxDistance + 1`, at most 4294967295 (enabling early termination
 * for better performance).
 */
export declare function levenshteinMany(reference: string, candidates: ReadonlyArray<string>, maxDistance?: number | undefined | null): Array<number>

/** Like `levenshteinMany`, but returns the distances in a `Uint32Array`. */
export declare function levenshteinManyU32(reference: string, candidates: ReadonlyArray<string>, maxDistance?: number | undefined | null): Uint32Array

/**
 * Classification of how a query matched an item.
 *
 * Derived from the matched character positions:
 * - **Exact**: all positions consecutive from index 0, covering every character in the item.
 * - **Prefix**: all positions consecutive from index 0, but the item is longer.
 * - **Contains**: all positions consecutive (a substring match), not starting at 0.
 * - **Fuzzy**: positions have gaps (character-level fuzzy match).
 */
export declare enum MatchType {
  Exact = 'Exact',
  Prefix = 'Prefix',
  Contains = 'Contains',
  Fuzzy = 'Fuzzy',
}

/**
 * Compute the normalized Hamming similarity between two strings.
 *
 * Returns `null` if the strings have different lengths.
 * Returns a value between 0.0 (no matching characters) and 1.0 (identical).
 *
 * Compares the Unicode code points of the strings as given: case, whitespace
 * and Unicode normalization (NFC vs NFD) are not adjusted.
 */
export declare function normalizedHamming(a: string, b: string): number | null

/**
 * Compute the normalized Hamming similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 * Returns `null` for pairs with different lengths.
 */
export declare function normalizedHammingBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number | undefined | null>

/**
 * Compute the normalized Hamming similarity from one reference string to many candidates.
 *
 * Returns an array of scores, one per candidate, in the same order as the input.
 * Returns `null` for candidates with a different length than the reference.
 * If `minSimilarity` is provided, candidates with similarity below the threshold
 * will also return `null`; a score equal to it is kept. Throws an `InvalidArg`
 * error if `minSimilarity` is `NaN`.
 */
export declare function normalizedHammingMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number | undefined | null>

/**
 * Like `normalizedHammingMany`, but returns the scores in a `Float64Array`.
 *
 * Slots that `normalizedHammingMany` returns as `null` (length mismatch, or
 * filtered out by `minSimilarity`) become `NaN`, since a Float64Array cannot
 * hold `null`. Check for it with `Number.isNaN(value)`.
 */
export declare function normalizedHammingManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

/**
 * Compute the normalized Indel similarity between two strings.
 *
 * `1 - indel(a, b) / (length of a + length of b)`, counted in characters:
 * the measure behind `fuzz.ratio` in RapidFuzz and fuzzball, on a 0.0-1.0
 * scale (fuzzball also lower-cases and strips punctuation by default; this
 * function does not). Returns a value between 0.0 (completely different)
 * and 1.0 (identical).
 *
 * Compares the Unicode code points of the strings as given: case, whitespace
 * and Unicode normalization (NFC vs NFD) are not adjusted.
 */
export declare function normalizedIndel(a: string, b: string): number

/**
 * Compute the normalized Indel similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function normalizedIndelBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the normalized Indel similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `minSimilarity` is provided, candidates with similarity below the threshold
 * will return `0.0` (enabling early termination for better performance); a score
 * equal to it is kept. Throws an `InvalidArg` error if `minSimilarity` is `NaN`.
 */
export declare function normalizedIndelMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number>

/** Like `normalizedIndelMany`, but returns the scores in a `Float64Array`. */
export declare function normalizedIndelManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

/**
 * Compute the normalized Levenshtein similarity between two strings.
 *
 * `1 - levenshtein(a, b) / max(length of a, length of b)`, counted in
 * characters. Returns a value between 0.0 (completely different) and 1.0
 * (identical).
 *
 * Compares the Unicode code points of the strings as given: case, whitespace
 * and Unicode normalization (NFC vs NFD) are not adjusted.
 */
export declare function normalizedLevenshtein(a: string, b: string): number

/**
 * Compute the normalized Levenshtein similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function normalizedLevenshteinBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the normalized Levenshtein similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `minSimilarity` is provided, candidates with similarity below the threshold
 * will return `0.0` (enabling early termination for better performance); a score
 * equal to it is kept. Throws an `InvalidArg` error if `minSimilarity` is `NaN`.
 */
export declare function normalizedLevenshteinMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number>

/** Like `normalizedLevenshteinMany`, but returns the scores in a `Float64Array`. */
export declare function normalizedLevenshteinManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

/**
 * Compute the partial ratio between two strings.
 *
 * Lower-cases both strings and collapses whitespace runs into single
 * spaces, then compares the shorter string with every window of the same
 * length in the longer one and returns the highest normalized Levenshtein
 * similarity. Useful when one string is a substring or truncation of the
 * other; it does not match abbreviations (`MSFT` vs `Microsoft` scores low).
 * Scores can differ from fuzzball's / RapidFuzz's `partial_ratio`, which
 * use a different alignment. Returns a value between 0.0 and 1.0.
 *
 * Takes time proportional to the length of the longer string times the
 * square of the length of the shorter one: about 0.4 s for a
 * 1,000-character string against a 10,000-character one with the native
 * addon.
 */
export declare function partialRatio(a: string, b: string): number

/**
 * Compute the partial ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function partialRatioBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the partial ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `minSimilarity` is provided, candidates scoring below the threshold return `0.0`;
 * a score equal to it is kept. Throws an `InvalidArg` error if `minSimilarity` is `NaN`.
 */
export declare function partialRatioMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number>

/** Like `partialRatioMany`, but returns the scores in a `Float64Array`. */
export declare function partialRatioManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

/**
 * Perform fuzzy search over a list of strings.
 *
 * Returns matches sorted by score (best match first).
 * Scores are normalized to a 0.0-1.0 range where 1.0 is a perfect match.
 * Uses the nucleo matcher (the one in the Helix editor): every character of
 * each query term must occur in the item in order, so letters missing from
 * the query are tolerated but substituted or swapped letters are not. Matches
 * at the start of the item, at word boundaries and in consecutive runs score
 * higher. Matching is smart case by default (see `SearchOptions`).
 *
 * Terms are separated by any whitespace (including the ideographic space
 * U+3000). A query without any search term (empty, whitespace-only or only
 * syntax such as `^`) returns no results, and so does a query containing a
 * single term longer than 2,520 characters, which cannot be scored.
 *
 * The third argument accepts either a number (maxResults for backward
 * compatibility) or a SearchOptions object with maxResults and minScore.
 * `maxResults` must be a non-negative integer or `Infinity`.
 */
export declare function search(query: string, items: ReadonlyArray<string>, options?: number | SearchOptions | undefined | null): Array<SearchResult>

/**
 * Perform fuzzy search across multiple text keys with weights.
 *
 * `keyTexts[k]` is an array of strings for key `k`, one per item.
 * All inner arrays must have the same length (the number of items).
 * `weights` specifies the relative importance of each key.
 *
 * By default every key is scored like `search()` scores an item, against
 * the whole query; with `matchMode: 'crossKey'` every term of the query is
 * matched against the keys on its own, so the terms may match different
 * keys (see `KeySearchOptions.matchMode`). `keyScores` holds the key
 * scores for every key, including keys whose weight is 0. By default the
 * combined score is `sum(keyScore * weight) / sum(weights)`; the
 * `scoreMode` option selects another way to combine them (see
 * `KeySearchOptions.scoreMode`). Items whose combined score is 0 (no match
 * on a key with a positive weight) are not returned.
 *
 * Returns results sorted by combined score (best match first), then by the
 * UTF-8 byte length of the best-matching key's text (shorter first, like
 * `search()`), then by index. `new KeyedFuzzyIndex(keyTexts, weights)`
 * returns exactly the same results.
 *
 * The fourth argument accepts either a number (maxResults) or a
 * KeySearchOptions object. Throws when the key texts have different lengths,
 * when there is not exactly one weight per key, or when a weight is
 * negative, NaN or infinite, or the weights sum to 0 or to Infinity (the
 * same errors as the `KeyedFuzzyIndex` constructor), and for an unknown
 * `scoreMode` or `matchMode`.
 */
export declare function searchKeys(query: string, keyTexts: ReadonlyArray<ReadonlyArray<string>>, weights: ReadonlyArray<number>, options?: number | KeySearchOptions | undefined | null): Array<KeySearchResult>

/** Options for the search function. */
export interface SearchOptions {
  /**
   * Maximum number of results to return: a non-negative integer, or
   * `Infinity` for no limit. NaN, negative and fractional values throw.
   */
  maxResults?: number | undefined
  /** Minimum normalized score (0.0-1.0) to include in results. */
  minScore?: number | undefined
  /** If true, include matched character positions in results. */
  includePositions?: boolean | undefined
  /**
   * If true, matching is case-sensitive. When false or omitted, matching
   * is smart case: case-insensitive while the query is all lower-case, and
   * case-sensitive once it contains an upper-case letter. `false` does not
   * force case-insensitive matching; lower-case the query for that.
   */
  isCaseSensitive?: boolean | undefined
  /**
   * If true, return all items when the query has no search term: empty,
   * whitespace-only, or only query syntax such as `^` or `!`.
   * Useful for filter-as-you-type UIs where the full list should appear
   * before the user starts typing. Default is false.
   */
  returnAllOnEmpty?: boolean | undefined
}

/** A single fuzzy search result with the matched item and its score. */
export interface SearchResult {
  /** The original string that matched. */
  item: string
  /** The match score normalized to 0.0-1.0 range (1.0 is a perfect match). */
  score: number
  /** The index of the item in the original input array. */
  index: number
  /**
   * Indices of the matched characters of the item, in ascending order.
   * An ASCII item is counted by character; any other item by grapheme
   * cluster (a user-perceived character, such as an emoji with its
   * modifiers or a letter with its combining marks), so these are not
   * UTF-16 string offsets. `highlight()` and `highlightRanges()` convert
   * them. Empty unless `includePositions` is set to true in SearchOptions.
   */
  positions: Array<number>
  /**
   * How the query matched this item (Exact, Prefix, Contains, or Fuzzy).
   * Only present when `includePositions` is set to true in SearchOptions.
   * Derived from positions at zero additional cost.
   */
  matchType?: MatchType
}

/**
 * Compute the Sorensen-Dice coefficient between two strings.
 *
 * Compares the bigrams (pairs of consecutive characters) of the two strings
 * after removing all whitespace; case and Unicode normalization are not
 * adjusted. Identical strings score 1.0; otherwise a string with fewer than
 * two characters left scores 0.0. Returns a value between 0.0 and 1.0.
 */
export declare function sorensenDice(a: string, b: string): number

/**
 * Compute the Sorensen-Dice coefficient for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function sorensenDiceBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the Sorensen-Dice coefficient from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `minSimilarity` is provided, candidates scoring below the threshold return `0.0`;
 * a score equal to it is kept. Throws an `InvalidArg` error if `minSimilarity` is `NaN`.
 * Reference bigrams are pre-computed once and reused for all candidates.
 */
export declare function sorensenDiceMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number>

/** Like `sorensenDiceMany`, but returns the scores in a `Float64Array`. */
export declare function sorensenDiceManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

/**
 * Compute the token set ratio between two strings.
 *
 * Lower-cases both strings and splits them into sets of whitespace-separated
 * tokens (duplicates count once). With the shared tokens sorted and joined
 * as `common`, returns the highest normalized Levenshtein similarity among
 * `common + rest of a` vs `common + rest of b`, `common` vs
 * `common + rest of a`, and `common` vs `common + rest of b`. It is 1.0
 * when the tokens of one string are a subset of the other's.
 * Returns a value between 0.0 and 1.0.
 */
export declare function tokenSetRatio(a: string, b: string): number

/**
 * Compute the token set ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function tokenSetRatioBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the token set ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `minSimilarity` is provided, candidates scoring below the threshold return `0.0`;
 * a score equal to it is kept. Throws an `InvalidArg` error if `minSimilarity` is `NaN`.
 */
export declare function tokenSetRatioMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number>

/** Like `tokenSetRatioMany`, but returns the scores in a `Float64Array`. */
export declare function tokenSetRatioManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

/**
 * Compute the token sort ratio between two strings.
 *
 * Lower-cases both strings, splits them on whitespace, sorts the tokens and
 * joins them with single spaces, then returns the normalized Levenshtein
 * similarity of the two results, so word order does not matter. Punctuation
 * is kept: `Smith,` and `Smith` are different tokens.
 * Returns a value between 0.0 (completely different) and 1.0 (identical after sorting).
 */
export declare function tokenSortRatio(a: string, b: string): number

/**
 * Compute the token sort ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function tokenSortRatioBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the token sort ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `minSimilarity` is provided, candidates scoring below the threshold return `0.0`;
 * a score equal to it is kept. Throws an `InvalidArg` error if `minSimilarity` is `NaN`.
 */
export declare function tokenSortRatioMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number>

/** Like `tokenSortRatioMany`, but returns the scores in a `Float64Array`. */
export declare function tokenSortRatioManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

/**
 * Compute the weighted ratio between two strings.
 *
 * Returns the highest of: the normalized Levenshtein similarity of the
 * strings as given and after lower-casing and collapsing whitespace,
 * `tokenSortRatio`, `tokenSetRatio` and `partialRatio`. Unlike `WRatio` in
 * fuzzball / RapidFuzz, no score is scaled down or weighted by the length
 * ratio of the strings, so scores are often higher than `WRatio`'s.
 * Includes the cost of `partialRatio` (see there) when the strings differ
 * in length. Returns a value between 0.0 and 1.0.
 */
export declare function weightedRatio(a: string, b: string): number

/**
 * Compute the weighted ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`; otherwise an
 * `InvalidArg` error is thrown.
 */
export declare function weightedRatioBatch(pairs: ReadonlyArray<ReadonlyArray<string>>): Array<number>

/**
 * Compute the weighted ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 * If `minSimilarity` is provided, candidates scoring below the threshold return `0.0`;
 * a score equal to it is kept. Throws an `InvalidArg` error if `minSimilarity` is `NaN`.
 */
export declare function weightedRatioMany(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Array<number>

/** Like `weightedRatioMany`, but returns the scores in a `Float64Array`. */
export declare function weightedRatioManyF64(reference: string, candidates: ReadonlyArray<string>, minSimilarity?: number | undefined | null): Float64Array

// --- JS utilities (appended by scripts/patch-binding.js) ---
export { highlight, highlightRanges, HighlightRange } from './highlight';

// --- JS wrappers (appended by scripts/patch-binding.js) ---
export { FuzzyObjectIndex, searchObjects } from './objects';
export type { KeyConfig, KeyPath, ObjectIndexOptions, ObjectIndexSearchOptions, ObjectSearchOptions, ObjectSearchResult } from './objects';
export type { HighlightOptions } from './highlight';
