import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const binding = require('./index.js');

export const {
  FuzzyIndex,
  KeyedFuzzyIndex,
  MatchType,
  closest,
  searchKeys,
  damerauLevenshtein,
  damerauLevenshteinBatch,
  damerauLevenshteinMany,
  hamming,
  hammingBatch,
  hammingMany,
  indel,
  indelBatch,
  indelMany,
  jaro,
  jaroBatch,
  jaroMany,
  jaroWinkler,
  jaroWinklerBatch,
  jaroWinklerMany,
  levenshtein,
  levenshteinBatch,
  levenshteinMany,
  normalizedHamming,
  normalizedHammingBatch,
  normalizedHammingMany,
  normalizedIndel,
  normalizedIndelBatch,
  normalizedIndelMany,
  normalizedLevenshtein,
  normalizedLevenshteinBatch,
  normalizedLevenshteinMany,
  partialRatio,
  partialRatioBatch,
  partialRatioMany,
  search,
  sorensenDice,
  sorensenDiceBatch,
  sorensenDiceMany,
  tokenSetRatio,
  tokenSetRatioBatch,
  tokenSetRatioMany,
  tokenSortRatio,
  tokenSortRatioBatch,
  tokenSortRatioMany,
  weightedRatio,
  weightedRatioBatch,
  weightedRatioMany,
  highlight,
  highlightRanges,
  levenshteinManyU32,
  damerauLevenshteinManyU32,
  indelManyU32,
  jaroManyF64,
  jaroWinklerManyF64,
  sorensenDiceManyF64,
  normalizedLevenshteinManyF64,
  normalizedIndelManyF64,
  tokenSortRatioManyF64,
  tokenSetRatioManyF64,
  partialRatioManyF64,
  weightedRatioManyF64,
  hammingManyU32,
  normalizedHammingManyF64,
} = { ...binding, ...require('./highlight.js') };

export const { searchObjects, FuzzyObjectIndex } = require('./objects.js');
