/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Find the closest matching string from a list.
 *
 * Returns the best match, or null if no match is found.
 * If minScore is provided, returns null when the best match scores below the threshold.
 */
export declare function closest(query: string, items: Array<string>, minScore?: number | undefined | null): string | null

/**
 * Compute the Damerau-Levenshtein distance between two strings.
 *
 * Like Levenshtein, but also considers transpositions of two adjacent
 * characters as a single edit.
 */
export declare function damerauLevenshtein(a: string, b: string): number

/**
 * Compute the Damerau-Levenshtein distance for multiple pairs of strings in a single call.
 *
 * Returns an array of distances in the same order as the input pairs.
 */
export declare function damerauLevenshteinBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Damerau-Levenshtein distance from one reference string to many candidates.
 *
 * Returns an array of distances, one per candidate, in the same order as the input.
 */
export declare function damerauLevenshteinMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the Jaro similarity between two strings.
 *
 * Returns a value between 0.0 (completely different) and 1.0 (identical).
 */
export declare function jaro(a: string, b: string): number

/**
 * Compute the Jaro similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function jaroBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Jaro similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function jaroMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the Jaro-Winkler similarity between two strings.
 *
 * A modification of Jaro that gives more weight to common prefixes.
 * Returns a value between 0.0 and 1.0.
 */
export declare function jaroWinkler(a: string, b: string): number

/**
 * Compute the Jaro-Winkler similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function jaroWinklerBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Jaro-Winkler similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function jaroWinklerMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the Levenshtein distance between two strings.
 *
 * The Levenshtein distance is the minimum number of single-character edits
 * (insertions, deletions, or substitutions) required to change one string
 * into the other.
 */
export declare function levenshtein(a: string, b: string): number

/**
 * Compute the Levenshtein distance for multiple pairs of strings in a single call.
 *
 * Returns an array of distances in the same order as the input pairs.
 * Each pair must be an array of exactly two strings `[a, b]`.
 */
export declare function levenshteinBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Levenshtein distance from one reference string to many candidates.
 *
 * Returns an array of distances, one per candidate, in the same order as the input.
 */
export declare function levenshteinMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the normalized Levenshtein similarity between two strings.
 *
 * Returns a value between 0.0 (completely different) and 1.0 (identical).
 */
export declare function normalizedLevenshtein(a: string, b: string): number

/**
 * Compute the normalized Levenshtein similarity for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function normalizedLevenshteinBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the normalized Levenshtein similarity from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function normalizedLevenshteinMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the partial ratio between two strings.
 *
 * Finds the best matching substring of the shorter string within the longer string
 * using a sliding window approach. Returns the highest normalized Levenshtein
 * similarity across all windows. Useful for matching when one string is a
 * substring or abbreviation of the other. Returns a value between 0.0 and 1.0.
 */
export declare function partialRatio(a: string, b: string): number

/**
 * Compute the partial ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function partialRatioBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the partial ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function partialRatioMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Perform fuzzy search over a list of strings.
 *
 * Returns matches sorted by score (best match first).
 * Scores are normalized to a 0.0-1.0 range where 1.0 is a perfect match.
 * Uses the nucleo algorithm (same as Helix editor), which is
 * significantly faster than fzf/skim for large datasets.
 *
 * The third argument accepts either a number (maxResults for backward
 * compatibility) or a SearchOptions object with maxResults and minScore.
 */
export declare function search(query: string, items: Array<string>, options?: number | SearchOptions | undefined | null): Array<SearchResult>

/** Options for the search function. */
export interface SearchOptions {
  /** Maximum number of results to return. */
  maxResults?: number
  /** Minimum normalized score (0.0-1.0) to include in results. */
  minScore?: number
  /** If true, include matched character positions in results. */
  includePositions?: boolean
}

/** A single fuzzy search result with the matched item and its score. */
export interface SearchResult {
  /** The original string that matched. */
  item: string
  /** The match score normalized to 0.0-1.0 range (1.0 is a perfect match). */
  score: number
  /** The index of the item in the original input array. */
  index: number
  /**
   * Indices of matched characters in the item string.
   * Empty unless `includePositions` is set to true in SearchOptions.
   */
  positions: Array<number>
}

/**
 * Compute the Sorensen-Dice coefficient between two strings.
 *
 * Uses bigrams (pairs of consecutive characters) to measure similarity.
 * Returns a value between 0.0 and 1.0.
 */
export declare function sorensenDice(a: string, b: string): number

/**
 * Compute the Sorensen-Dice coefficient for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function sorensenDiceBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the Sorensen-Dice coefficient from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function sorensenDiceMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the token set ratio between two strings.
 *
 * Compares the intersection and differences of token sets from both strings.
 * Returns the maximum similarity among comparisons of the intersection with
 * each remainder. Highly effective for strings with shared tokens but
 * different lengths. Returns a value between 0.0 and 1.0.
 */
export declare function tokenSetRatio(a: string, b: string): number

/**
 * Compute the token set ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function tokenSetRatioBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the token set ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function tokenSetRatioMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the token sort ratio between two strings.
 *
 * Splits both strings into tokens, sorts them alphabetically, then computes
 * the normalized Levenshtein similarity. This makes the comparison
 * order-independent, ideal for matching names or addresses where word order varies.
 * Returns a value between 0.0 (completely different) and 1.0 (identical after sorting).
 */
export declare function tokenSortRatio(a: string, b: string): number

/**
 * Compute the token sort ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function tokenSortRatioBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the token sort ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function tokenSortRatioMany(reference: string, candidates: Array<string>): Array<number>

/**
 * Compute the weighted ratio between two strings.
 *
 * Returns the maximum score across normalized Levenshtein, token sort ratio,
 * token set ratio, and partial ratio. This provides a single "best effort"
 * similarity score that automatically selects the most appropriate algorithm.
 * Returns a value between 0.0 and 1.0.
 */
export declare function weightedRatio(a: string, b: string): number

/**
 * Compute the weighted ratio for multiple pairs of strings in a single call.
 *
 * Returns an array of similarity scores in the same order as the input pairs.
 */
export declare function weightedRatioBatch(pairs: Array<Array<string>>): Array<number>

/**
 * Compute the weighted ratio from one reference string to many candidates.
 *
 * Returns an array of similarity scores, one per candidate, in the same order as the input.
 */
export declare function weightedRatioMany(reference: string, candidates: Array<string>): Array<number>
