// Generated by scripts/build-browser.js: do not edit.
// Declarations of "rapid-fuzzy/objects" in browsers and edge runtimes.
export { FuzzyObjectIndex, searchObjects } from './browser.mjs';
export type {
  KeyConfig,
  ObjectSearchOptions,
  ObjectSearchResult,
  ObjectIndexOptions,
  ObjectIndexSearchOptions,
} from './objects.js';
