interface Window {
  __ready?: boolean;
  __error?: string;
  __results: {
    levenshtein: number;
    levenshteinIdentical: number;
    normalizedLevenshtein: number;
    damerauLevenshtein: number;
    jaro: number;
    jaroWinkler: number;
    sorensenDice: number;
    hamming: number;
    hammingNull: number | null;
    indel: number;
    normalizedIndel: number;
    normalizedHamming: number;
    normalizedHammingNull: number | null;
    levenshteinBatch: number[];
    jaroBatch: number[];
    hammingBatch: (number | null)[];
    indelBatch: number[];
    normalizedIndelBatch: number[];
    normalizedHammingBatch: (number | null)[];
    levenshteinMany: number[];
    jaroMany: number[];
    hammingMany: (number | null)[];
    indelMany: number[];
    normalizedIndelMany: number[];
    normalizedHammingMany: (number | null)[];
    tokenSortRatio: number;
    tokenSetRatio: number;
    partialRatio: number;
    weightedRatio: number;
    search: Array<{ item: string; score: number; index: number; positions: number[] }>;
    searchEmpty: Array<{ item: string; score: number; index: number; positions: number[] }>;
    closest: string | null;
    closestEmpty: string | null;
    indexSize: number;
    indexSearch: Array<{ item: string; score: number; index: number; positions: number[] }>;
    indexClosest: string | null;
    indexSizeAfterAdd: number;
    indexSizeAfterDestroy: number;
    levenshteinManyU32: { typed: boolean; values: number[] };
    hammingManyU32: number[];
    matchType: string | undefined;
    matchTypeEnum: Record<string, string>;
    highlight: string;
    highlightSubpath: string;
    highlightRanges: Array<{ start: number; end: number; matched: boolean }>;
    searchObjects: string[];
    objectIndexSearch: string[];
    objectIndexClosest: string | null;
    objectIndexSize: number;
    objectsFromMainEntry: boolean;
    exports: string[];
    wasmRequests: string[];
  };
}
