#!/usr/bin/env node
/**
 * Generate the browser / edge entry points of the package from the
 * wasm-bindgen glue and the CommonJS JS wrappers.
 *
 * Inputs (committed):
 *   rapid-fuzzy-wasm-bindgen.mjs / .d.mts   wasm-bindgen `--target web` output
 *   highlight.js, objects.js                 CommonJS sources (also used by Node.js)
 *   highlight.d.ts, objects.d.ts             their declarations
 *
 * Outputs (committed, regenerated by `pnpm run build`, `pnpm run build:wasm-bindgen`
 * and `node scripts/patch-binding.js`):
 *   browser.mjs            "browser" / "deno" entry: instantiates the WebAssembly
 *                          module with top-level await, then exposes the API
 *   workerd.mjs            "workerd" entry (Cloudflare Workers): imports the .wasm as a
 *                          precompiled WebAssembly.Module and instantiates it
 *                          synchronously
 *   browser-api.mjs        the API both entries expose (glue + JS-only utilities)
 *   highlight.browser.mjs  ES module build of highlight.js
 *   objects.browser.mjs    ES module build of objects.js on top of the glue
 *   browser.d.mts          declarations of browser.mjs / workerd.mjs
 *   objects.browser.d.mts  declarations of the "rapid-fuzzy/objects" browser entry
 *
 * The CommonJS sources stay the single source of truth: their ES module builds
 * wrap the unmodified source in a function scope that provides `module`,
 * `exports` and a `require` resolved at build time, so every module in the
 * browser graph is plain ESM (loadable without a bundler, e.g. from a CDN).
 *
 * Usage: node scripts/build-browser.js
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const GLUE = 'rapid-fuzzy-wasm-bindgen.mjs';
const GLUE_DTS = 'rapid-fuzzy-wasm-bindgen.d.mts';
const WASM = 'rapid-fuzzy-wasm-bindgen_bg.wasm';

// Declarations of the wasm-bindgen initialization API, which the entries call
// themselves and do not re-export.
const INIT_EXPORTS = new Set(['initSync', 'InitInput', 'InitOutput', 'SyncInitInput']);

// The wasm-bindgen *Many functions already return typed arrays, so the
// TypedArray variants of the Node.js binding are the same functions.
const TYPED_ARRAY_ALIASES = {
  levenshteinManyU32: 'levenshteinMany',
  damerauLevenshteinManyU32: 'damerauLevenshteinMany',
  indelManyU32: 'indelMany',
  jaroManyF64: 'jaroMany',
  jaroWinklerManyF64: 'jaroWinklerMany',
  sorensenDiceManyF64: 'sorensenDiceMany',
  normalizedLevenshteinManyF64: 'normalizedLevenshteinMany',
  normalizedIndelManyF64: 'normalizedIndelMany',
  tokenSortRatioManyF64: 'tokenSortRatioMany',
  tokenSetRatioManyF64: 'tokenSetRatioMany',
  partialRatioManyF64: 'partialRatioMany',
  weightedRatioManyF64: 'weightedRatioMany',
};

// Exports the entry points implement in JavaScript on top of the glue.
const JS_ONLY_EXPORTS = [
  ...Object.keys(TYPED_ARRAY_ALIASES),
  'hammingManyU32',
  'normalizedHammingManyF64',
  'MatchType',
  'highlight',
  'highlightRanges',
  'FuzzyObjectIndex',
  'searchObjects',
];

// Modules the CommonJS wrappers may require(), and the ES module code that
// provides each of them in the browser build.
const REQUIRE_PROVIDERS = {
  // objects.js: `const { ... } = require('./index.js')` resolves to the glue.
  './index.js': (names) => ({
    imports: [`import { ${names.join(', ')} } from './${GLUE}';`],
    value: `{ ${names.join(', ')} }`,
  }),
  // Argument checks may use util.types, which browsers lack.
  'node:util': () => ({
    imports: [],
    value:
      "{ types: { isAnyArrayBuffer: (value) => value instanceof ArrayBuffer || (typeof SharedArrayBuffer === 'function' && value instanceof SharedArrayBuffer) } }",
  }),
};

function read(file) {
  return fs.readFileSync(path.join(ROOT, file), 'utf8');
}

function header(description, source) {
  const from = source ? ` from ${source}` : '';
  return [`// Generated by scripts/build-browser.js${from}: do not edit.`, ...description];
}

function exportList(names, from, keyword = 'export') {
  return `${keyword} {\n${names.map((n) => `  ${n},`).join('\n')}\n} from './${from}';`;
}

/** Value and type exports of the glue, without the initialization API. */
function glueExports() {
  const js = read(GLUE);
  const dts = read(GLUE_DTS);
  const values = [...js.matchAll(/^export (?:class|function) (\w+)/gm)]
    .map((m) => m[1])
    .filter((n) => !INIT_EXPORTS.has(n));
  const declaredValues = new Set(
    [...dts.matchAll(/^export (?:declare )?(?:class|function) (\w+)/gm)].map((m) => m[1]),
  );
  for (const name of values) {
    if (!declaredValues.has(name)) {
      throw new Error(`build-browser: ${GLUE} exports ${name}, which ${GLUE_DTS} lacks`);
    }
  }
  const types = [...dts.matchAll(/^export (?:interface|type) (\w+)/gm)]
    .map((m) => m[1])
    .filter((n) => !INIT_EXPORTS.has(n));
  for (const required of ['search', 'FuzzyIndex', 'KeyedFuzzyIndex', 'searchKeys']) {
    if (!values.includes(required)) {
      throw new Error(`build-browser: ${GLUE} does not export ${required}`);
    }
  }
  // The entries add these in JavaScript; a glue export of the same name would
  // be a duplicate export (a SyntaxError when the entry is loaded).
  for (const name of JS_ONLY_EXPORTS) {
    if (values.includes(name)) {
      throw new Error(
        `build-browser: ${GLUE} now exports ${name}; remove its JavaScript version from scripts/build-browser.js`,
      );
    }
  }
  const matchType = /^export type MatchType = (.+);$/m.exec(dts);
  if (!matchType) {
    throw new Error(`build-browser: MatchType not found in ${GLUE_DTS}`);
  }
  const matchTypes = [...matchType[1].matchAll(/"(\w+)"/g)].map((m) => m[1]);
  return { values, types, matchTypes };
}

/** Exported value and type names declared in a .d.ts file. */
function declarationExports(file) {
  const dts = read(file);
  return {
    values: [...dts.matchAll(/^export declare (?:class|function) (\w+)/gm)].map((m) => m[1]),
    types: [...new Set([...dts.matchAll(/^export (?:interface|type) (\w+)/gm)].map((m) => m[1]))],
  };
}

/**
 * Wrap a CommonJS module as an ES module. `exportNames` must all be assigned
 * to `module.exports`; every require() must have a REQUIRE_PROVIDERS entry.
 */
function wrapCommonJs(file, exportNames, description, epilogue = []) {
  const source = read(file);
  const imports = [];
  const provided = [];
  const ids = [...new Set([...source.matchAll(/\brequire\((['"])(.+?)\1\)/g)].map((m) => m[2]))];
  for (const id of ids) {
    const provider = REQUIRE_PROVIDERS[id];
    if (!provider) {
      throw new Error(
        `build-browser: ${file} requires '${id}', which has no browser equivalent in REQUIRE_PROVIDERS`,
      );
    }
    const destructured = new RegExp(
      `const \\{([^}]*)\\} = require\\((['"])${id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\2\\)`,
    ).exec(source);
    if (!destructured) {
      throw new Error(`build-browser: ${file} must destructure require('${id}')`);
    }
    const names = destructured[1]
      .split(',')
      .map((n) => n.trim())
      .filter(Boolean);
    const { imports: providerImports, value } = provider(names);
    imports.push(...providerImports);
    provided.push(`  ${JSON.stringify(id)}: ${value},`);
  }
  for (const name of exportNames) {
    const assigned =
      new RegExp(`module\\.exports\\.${name}\\s*=`).test(source) ||
      new RegExp(`module\\.exports\\s*=\\s*\\{[^}]*\\b${name}\\b[^}]*\\}`).test(source);
    if (!assigned) {
      throw new Error(`build-browser: ${file} does not export ${name}`);
    }
  }
  return [
    ...header(description, file),
    ...imports,
    '',
    'const __modules = {',
    ...provided,
    '};',
    'const __module = { exports: {} };',
    '',
    '(function (module, exports, require) {',
    source.trimEnd(),
    '})(__module, __module.exports, (id) => __modules[id]);',
    '',
    `export const { ${exportNames.join(', ')} } = __module.exports;`,
    ...epilogue,
    '',
  ].join('\n');
}

function browserApi({ values, matchTypes }) {
  const aliased = Object.values(TYPED_ARRAY_ALIASES);
  const imported = [...new Set([...aliased, 'hammingMany', 'normalizedHammingMany'])].sort();
  for (const name of imported) {
    if (!values.includes(name)) throw new Error(`build-browser: ${GLUE} does not export ${name}`);
  }
  return [
    ...header([
      '// The rapid-fuzzy API on top of the wasm-bindgen glue, shared by the browser.mjs',
      '// and workerd.mjs entry points (which instantiate the WebAssembly module first).',
    ]),
    `import { ${imported.join(', ')} } from './${GLUE}';`,
    '',
    exportList(values, GLUE),
    "export { highlight, highlightRanges } from './highlight.browser.mjs';",
    "export { FuzzyObjectIndex, searchObjects } from './objects.browser.mjs';",
    '',
    '// Runtime values of the MatchType string enum (the Node.js binding exports the same object).',
    `export const MatchType = Object.freeze({ ${matchTypes.map((n) => `${n}: '${n}'`).join(', ')} });`,
    '// TypedArray variants: the wasm-bindgen *Many functions already return typed arrays.',
    ...Object.entries(TYPED_ARRAY_ALIASES).map(([alias, fn]) => `export const ${alias} = ${fn};`),
    '// Same sentinels as index.js: 0xffffffff / NaN where hammingMany returns null.',
    'export const hammingManyU32 = (r, c, d) => Uint32Array.from(hammingMany(r, c, d), (v) => (v == null ? 0xffffffff : v));',
    'export const normalizedHammingManyF64 = (r, c, s) => Float64Array.from(normalizedHammingMany(r, c, s), (v) => (v == null ? Number.NaN : v));',
    '',
  ].join('\n');
}

/** Every name the entry points export (runtime and declarations agree on this list). */
function apiNames({ values }) {
  return [
    ...values,
    'highlight',
    'highlightRanges',
    'FuzzyObjectIndex',
    'searchObjects',
    'MatchType',
    ...Object.keys(TYPED_ARRAY_ALIASES),
    'hammingManyU32',
    'normalizedHammingManyF64',
  ];
}

function browserEntry(glue) {
  return [
    ...header([
      '// rapid-fuzzy for browsers, bundlers and Deno: the wasm-bindgen WebAssembly build.',
      '// The module is instantiated with top-level await, so the API is ready to use',
      '// (synchronously) once the import has resolved.',
    ]),
    `import init from './${GLUE}';`,
    '',
    '// Bundlers (Vite, webpack, Rollup, Parcel) emit the .wasm referenced by this',
    '// `new URL(..., import.meta.url)` as an asset; without a bundler it is fetched',
    '// next to this file.',
    `const wasmUrl = new URL('./${WASM}', import.meta.url);`,
    '// fetch() cannot read file: URLs in Node.js (e.g. under --conditions=browser);',
    '// read the file directly where the runtime provides process.getBuiltinModule().',
    "const fs = wasmUrl.protocol === 'file:' ? globalThis.process?.getBuiltinModule?.('node:fs') : undefined;",
    'await init({ module_or_path: fs === undefined ? wasmUrl : fs.readFileSync(wasmUrl) });',
    '',
    exportList(apiNames(glue), 'browser-api.mjs'),
    '',
  ].join('\n');
}

function workerdEntry(glue) {
  return [
    ...header([
      '// rapid-fuzzy for Cloudflare Workers (the "workerd" export condition). Workers',
      '// cannot compile WebAssembly from bytes at runtime; Wrangler bundles the',
      '// `.wasm?module` import below as a precompiled WebAssembly.Module instead, which',
      '// is instantiated synchronously at startup.',
    ]),
    `import wasmModule from './${WASM}?module';`,
    `import { initSync } from './${GLUE}';`,
    '',
    'initSync({ module: wasmModule });',
    '',
    exportList(apiNames(glue), 'browser-api.mjs'),
    '',
  ].join('\n');
}

function browserDeclarations(glue, objects, highlight) {
  const typedArrayImports = [
    ...new Set([...Object.values(TYPED_ARRAY_ALIASES), 'hammingMany', 'normalizedHammingMany']),
  ].sort();
  return [
    ...header([
      '// Declarations of the browser and edge entry points (browser.mjs, workerd.mjs):',
      '// the API of the wasm-bindgen build, without the Node.js-only parts of index.d.ts.',
    ]),
    "import type { FuzzyObjectIndex as NodeFuzzyObjectIndex } from './objects.js';",
    `import type { MatchType as MatchTypeUnion, ${typedArrayImports.join(', ')} } from './${GLUE}';`,
    '',
    exportList(glue.values, GLUE),
    exportList(
      glue.types.filter((n) => n !== 'MatchType'),
      GLUE,
      'export type',
    ),
    "export { highlight, highlightRanges } from './highlight.js';",
    exportList(highlight.types, 'highlight.js', 'export type'),
    "export { searchObjects } from './objects.js';",
    exportList(objects.types, 'objects.js', 'export type'),
    '',
    '/**',
    ' * The Node.js `FuzzyObjectIndex` without `serialize()` and `deserialize()`, which',
    ' * exchange Node.js Buffers.',
    ' */',
    "export interface FuzzyObjectIndex<T> extends Omit<NodeFuzzyObjectIndex<T>, 'serialize'> {}",
    'export declare const FuzzyObjectIndex: new <T>(',
    '  ...args: ConstructorParameters<typeof NodeFuzzyObjectIndex<T>>',
    ') => FuzzyObjectIndex<T>;',
    '',
    '/** How a search result matched the query. */',
    'export type MatchType = MatchTypeUnion;',
    '/** Runtime values of the {@link MatchType} string enum. */',
    `export declare const MatchType: { ${glue.matchTypes.map((n) => `readonly ${n}: '${n}';`).join(' ')} };`,
    '',
    ...Object.entries(TYPED_ARRAY_ALIASES).flatMap(([alias, fn]) => [
      `/** TypedArray variant of {@link ${fn}}: the same function, which already returns a typed array. */`,
      `export declare const ${alias}: typeof ${fn};`,
    ]),
    '/**',
    ' * TypedArray variant of {@link hammingMany}. Slots that `hammingMany` returns as `null`',
    ' * become the sentinel `0xffffffff` (4294967295).',
    ' */',
    'export declare function hammingManyU32(...args: Parameters<typeof hammingMany>): Uint32Array;',
    '/**',
    ' * TypedArray variant of {@link normalizedHammingMany}. Slots that',
    ' * `normalizedHammingMany` returns as `null` become `NaN`.',
    ' */',
    'export declare function normalizedHammingManyF64(',
    '  ...args: Parameters<typeof normalizedHammingMany>',
    '): Float64Array;',
    '',
  ].join('\n');
}

function objectsBrowserDeclarations(objects) {
  return [
    ...header(['// Declarations of "rapid-fuzzy/objects" in browsers and edge runtimes.']),
    "export { FuzzyObjectIndex, searchObjects } from './browser.mjs';",
    exportList(objects.types, 'objects.js', 'export type'),
    '',
  ].join('\n');
}

/** The generated files, as a map from file name to content. */
function render() {
  const glue = glueExports();
  const objects = declarationExports('objects.d.ts');
  const highlight = declarationExports('highlight.d.ts');
  for (const [file, expected] of [
    ['objects.d.ts', ['searchObjects', 'FuzzyObjectIndex']],
    ['highlight.d.ts', ['highlight', 'highlightRanges']],
  ]) {
    const declared = (file === 'objects.d.ts' ? objects : highlight).values;
    for (const name of expected) {
      if (!declared.includes(name)) throw new Error(`build-browser: ${file} lacks ${name}`);
    }
  }
  const source = read('objects.js');
  if (!/\n {2}serialize\(\) \{/.test(source) || !/\n {2}static deserialize\(/.test(source)) {
    throw new Error('build-browser: objects.js no longer defines serialize() / deserialize()');
  }

  return {
    'highlight.browser.mjs': wrapCommonJs(
      'highlight.js',
      ['highlight', 'highlightRanges'],
      ['// ES module build of highlight.js for browsers and edge runtimes.'],
    ),
    'objects.browser.mjs': wrapCommonJs(
      'objects.js',
      ['searchObjects', 'FuzzyObjectIndex'],
      [
        '// ES module build of objects.js for browsers and edge runtimes, running on the',
        '// wasm-bindgen glue instead of the Node-API addon.',
      ],
      [
        '',
        '// serialize() and deserialize() exchange Node.js Buffers, which browsers and edge',
        '// runtimes lack: they are not part of this build.',
        'delete FuzzyObjectIndex.prototype.serialize;',
        'delete FuzzyObjectIndex.deserialize;',
      ],
    ),
    'browser-api.mjs': browserApi(glue),
    'browser.mjs': browserEntry(glue),
    'workerd.mjs': workerdEntry(glue),
    'browser.d.mts': browserDeclarations(glue, objects, highlight),
    'objects.browser.d.mts': objectsBrowserDeclarations(objects),
  };
}

function generate() {
  for (const [file, content] of Object.entries(render())) {
    fs.writeFileSync(path.join(ROOT, file), content);
    console.log(`  generated ${file}`);
  }
}

module.exports = { generate, render };

if (require.main === module) {
  generate();
}
