/**
 * Rewrites shared by the scripts that post-process generated TypeScript
 * declarations: scripts/patch-binding.js (index.d.ts, generated by napi-rs)
 * and scripts/build-wasm-bindgen.js (rapid-fuzzy-wasm-bindgen.d.mts,
 * generated by wasm-bindgen and tsify), so that both builds declare their
 * options objects the same way.
 */

'use strict';

/**
 * The options objects the bindings read from JavaScript. Both builds treat a
 * field set to `undefined` like a missing one: the Node.js binding reads each
 * field with `Object::get`, which returns `None` for `undefined`, and in the
 * WebAssembly build every field is an `Option` with `#[serde(default)]`, which
 * serde-wasm-bindgen leaves unset for `undefined`.
 */
const INPUT_INTERFACES = ['SearchOptions', 'KeySearchOptions', 'KeyClosestOptions'];

/**
 * The objects the bindings return: an optional field that is not set is
 * omitted, never present as `undefined`.
 */
const OUTPUT_INTERFACES = ['SearchResult', 'IndexSearchResult'];

/** An optional field: `  name?: Type` (napi-rs) or `    name?: Type;` (tsify). */
const OPTIONAL_FIELD = /^(\s+\w+\?: )(.+?)(;?)$/gm;

/** The `[start, end)` range of the body of `export interface name`, or null. */
function interfaceBody(dts, name) {
  const start = dts.indexOf(`export interface ${name} {`);
  const end = start === -1 ? -1 : dts.indexOf('\n}', start);
  return end === -1 ? null : [start, end];
}

/** The names of the exported interfaces of `dts` that declare an optional field. */
function interfacesWithOptionalFields(dts) {
  const optional = new RegExp(OPTIONAL_FIELD.source, 'm');
  return [...dts.matchAll(/^export interface (\w+) \{/gm)]
    .map((m) => m[1])
    .filter((name) => {
      const [start, end] = interfaceBody(dts, name) ?? [0, 0];
      return optional.test(dts.slice(start, end));
    });
}

/**
 * Let the optional fields of the interface `name` accept an explicit
 * `undefined` (`field?: T | undefined`), as required under
 * `exactOptionalPropertyTypes`. Idempotent.
 */
function optionalFieldsAcceptUndefined(dts, name, file) {
  const range = interfaceBody(dts, name);
  if (range === null) {
    throw new Error(`${file}: interface ${name} not found`);
  }
  const [start, end] = range;
  const body = dts
    .slice(start, end)
    .replace(OPTIONAL_FIELD, (field, head, type, semicolon) =>
      /\bundefined\b/.test(type) ? field : `${head}${type} | undefined${semicolon}`,
    );
  return dts.slice(0, start) + body + dts.slice(end);
}

/**
 * Let every optional field of the input interfaces (INPUT_INTERFACES) accept
 * an explicit `undefined`, as the bindings do. Throws if an interface with
 * optional fields is neither an input nor an output interface, so that a new
 * one is classified. Idempotent.
 *
 * @param {string} dts - The declarations.
 * @param {string} file - The declaration file, for errors.
 * @returns {string}
 */
function inputFieldsAcceptUndefined(dts, file) {
  for (const name of interfacesWithOptionalFields(dts)) {
    if (!INPUT_INTERFACES.includes(name) && !OUTPUT_INTERFACES.includes(name)) {
      throw new Error(
        `${file}: interface ${name} has optional fields; add it to INPUT_INTERFACES or OUTPUT_INTERFACES in scripts/declarations.js`,
      );
    }
  }
  let rewritten = dts;
  for (const name of INPUT_INTERFACES) {
    rewritten = optionalFieldsAcceptUndefined(rewritten, name, file);
  }
  return rewritten;
}

module.exports = { inputFieldsAcceptUndefined };
